# Environment: OpenAI GYM

In [11]:
import gym
import random
import numpy as np

In [3]:
env = gym.make('MountainCar-v0')
states = env.observation_space.shape[0]
actions = env.action_space.n

states, actions

(2, 3)

In [4]:
episodes = 10

for episode in range(1, episodes + 1):
    state = env.reset()
    done = False
    score = 0
    while not done:
        env.render()
        action = random.choice([0, 1, 2])
        new_state, reward, done, _ = env.step(action)
        score += reward
    print('Episode: {} Scoure: {}'.format(episode, score))
env.close()

Episode: 1 Scoure: -200.0
Episode: 2 Scoure: -200.0
Episode: 3 Scoure: -200.0
Episode: 4 Scoure: -200.0
Episode: 5 Scoure: -200.0
Episode: 6 Scoure: -200.0
Episode: 7 Scoure: -200.0
Episode: 8 Scoure: -200.0
Episode: 9 Scoure: -200.0
Episode: 10 Scoure: -200.0


In [5]:
episodes = 1

for episode in range(1, episodes + 1):
    state = env.reset()
    done = False
    score = 0
    while not done:
        env.render()
        action = random.choice([0, 1, 2])
        new_state, reward, done, info = env.step(action)
        print(action, new_state, reward, done, info)
        score += reward
    print('Episode: {} Scoure: {}'.format(episode, score))
env.close()

0 [-0.41316302 -0.00182614] -1.0 False {}
0 [-0.41680236 -0.00363934] -1.0 False {}
2 [-0.42022903 -0.00342668] -1.0 False {}
0 [-0.42541862 -0.00518958] -1.0 False {}
0 [-0.43233395 -0.00691533] -1.0 False {}
1 [-0.43992525 -0.0075913 ] -1.0 False {}
2 [-0.44713753 -0.00721228] -1.0 False {}
2 [-0.45391826 -0.00678072] -1.0 False {}
2 [-0.46021779 -0.00629953] -1.0 False {}
2 [-0.46598982 -0.00577203] -1.0 False {}
0 [-0.47319177 -0.00720195] -1.0 False {}
1 [-0.48077033 -0.00757856] -1.0 False {}
0 [-0.48966922 -0.00889889] -1.0 False {}
2 [-0.49782215 -0.00815292] -1.0 False {}
1 [-0.5061682  -0.00834606] -1.0 False {}
1 [-0.51464493 -0.00847673] -1.0 False {}
1 [-0.5231888  -0.00854387] -1.0 False {}
1 [-0.53173575 -0.00854695] -1.0 False {}
0 [-0.54122167 -0.00948593] -1.0 False {}
0 [-0.55157549 -0.01035382] -1.0 False {}
2 [-0.56071973 -0.00914424] -1.0 False {}
2 [-0.56858613 -0.0078664 ] -1.0 False {}
0 [-0.57711615 -0.00853002] -1.0 False {}
2 [-0.58424652 -0.00713036] -1.0 F

# Q Table :

In [9]:
high = env.observation_space.high
low = env.observation_space.low

high, low, actions

(array([0.6 , 0.07], dtype=float32), array([-1.2 , -0.07], dtype=float32), 3)

In [10]:
DISCRETE_OS_SIZE = [20] * len(high)
discrete_os_win_size = (high - low) / DISCRETE_OS_SIZE

DISCRETE_OS_SIZE, discrete_os_win_size

([20, 20], array([0.09 , 0.007]))

In [15]:
q_table = np.random.uniform(low=-2, high=0, size=(DISCRETE_OS_SIZE + [actions]))

q_table, q_table.shape

(array([[[-0.07756931, -0.32752699, -0.49295921],
         [-1.58777135, -0.8781839 , -0.35739713],
         [-0.0306508 , -0.27146894, -1.07354086],
         ...,
         [-0.79812365, -1.89165595, -1.21599493],
         [-0.29315099, -0.66938371, -0.13350849],
         [-1.35507029, -0.26198008, -1.60767721]],
 
        [[-0.08960482, -0.55963549, -0.75136971],
         [-1.12810801, -0.68208703, -1.02810345],
         [-0.93324133, -0.5740921 , -0.72539095],
         ...,
         [-1.89208149, -1.57326174, -0.68347977],
         [-1.12416492, -0.53180565, -0.1720236 ],
         [-0.37930416, -0.9518947 , -1.26524483]],
 
        [[-1.01032751, -0.4374398 , -0.27307617],
         [-1.02054809, -0.96846321, -0.24546888],
         [-0.71735231, -0.80317718, -0.39307918],
         ...,
         [-0.24279219, -0.57675247, -1.59525209],
         [-1.65089115, -1.4875709 , -1.4145783 ],
         [-1.18832602, -0.54955101, -0.71952929]],
 
        ...,
 
        [[-1.46447887, -0.49538906

In [145]:
LEARNING_RATE = .1  # 0 --> 1
DISCOUNT = 0.95     # 0 --> 1
EPISODES = 25000
GOAL_POSITION = env.goal_position
SHOW = 500
ACTIONS = {}
LEARNING_RATE, DISCOUNT, EPISODES, GOAL_POSITION, SHOW

(0.1, 0.95, 25000, 0.5, 500)

In [122]:
def get_discrete_state(state):
    discrete_state = (state - env.observation_space.low)/discrete_os_win_size
    return tuple(discrete_state.astype(np.int_))

In [123]:
discrete_state = get_discrete_state(env.reset())

discrete_state

(8, 10)

In [110]:
comb = q_table[discrete_state]
action = np.argmax(q_table[discrete_state])

comb, action

(array([[[-0.08863616, -0.19806168, -0.8745373 ],
         [-0.76081608, -0.46552345, -0.30270493],
         [-0.13600974, -0.38461601, -1.96518904],
         [-0.2743365 , -0.68336981, -0.41649827],
         [-0.12010344, -0.22840809, -0.06429342],
         [-0.41419636, -0.27363089, -0.06918972],
         [-1.1274758 , -1.3141273 , -1.15266556],
         [-1.94570772, -0.32545132, -0.22263577],
         [-1.04446892, -0.18027005, -1.86578233],
         [-0.59546855, -0.50785798, -0.49830777],
         [-1.72893488, -1.19623389, -0.68924636],
         [-0.40948296, -1.03492401, -0.05958527],
         [-0.56564542, -1.02886805, -1.85915115],
         [-0.9238944 , -1.9016411 , -1.61270456],
         [-1.35658998, -0.03817563, -1.50816129],
         [-0.82363856, -1.67468711, -1.87930739],
         [-0.17862648, -1.69149225, -1.07222402],
         [-1.0422173 , -1.67454874, -0.66163946],
         [-0.58386809, -1.42460697, -1.50364367],
         [-0.26970967, -1.16796345, -0.94963653]],

# Building Model

#### Q learning formula:

![<caption>](img/Q_learning.jpg)

![<caption>](img/desc.jpg)

In [124]:
def get_new_q(discrete_state, action, new_discrete_state, reward):
    max_future_q = np.max(q_table[new_discrete_state])
    current_q = q_table[discrete_state + (action, )]
    new_q = ((1 - LEARNING_RATE)*current_q ) + (LEARNING_RATE * DISCOUNT * max_future_q) + (LEARNING_RATE*reward)
    q_table[discrete_state + (action, )] = new_q
    

In [143]:
def build_model():
    for episode in range(EPISODES):
        # if episode % SHOW == 0:
        #     print("--------------SHOW-------------")
        #     print(episode)
        #     render = True
        # else:
        #     render = False
        discrete_state = get_discrete_state(env.reset())
        done = False
        e_actions = []
        while not done:
            
            # if render:
            #     env.render()
            action = np.argmax(q_table[discrete_state])
            e_actions.append(action)
            new_state, reward, done, _ = env.step(action)
            
            new_discrete_state = get_discrete_state(new_state)
            if not done:
                get_new_q(discrete_state, action, new_discrete_state, reward)
            elif new_state[0] >= GOAL_POSITION:
                print(f"WE MADE IT ON EPISODE {episode}")
                q_table[discrete_state + (action, )] = 0
            discrete_state = new_discrete_state
        ACTIONS[episode] = e_actions
        env.close()

# Training The Model

In [47]:
q_table 

array([[[-0.07756931, -0.32752699, -0.49295921],
        [-1.58777135, -0.8781839 , -0.35739713],
        [-0.0306508 , -0.27146894, -1.07354086],
        ...,
        [-0.79812365, -1.89165595, -1.21599493],
        [-0.29315099, -0.66938371, -0.13350849],
        [-1.35507029, -0.26198008, -1.60767721]],

       [[-0.08960482, -0.55963549, -0.75136971],
        [-1.12810801, -0.68208703, -1.02810345],
        [-0.93324133, -0.5740921 , -0.72539095],
        ...,
        [-1.89208149, -1.57326174, -0.68347977],
        [-1.12416492, -0.53180565, -0.1720236 ],
        [-0.37930416, -0.9518947 , -1.26524483]],

       [[-1.01032751, -0.4374398 , -0.27307617],
        [-1.02054809, -0.96846321, -0.24546888],
        [-0.71735231, -0.80317718, -0.39307918],
        ...,
        [-0.24279219, -0.57675247, -1.59525209],
        [-1.65089115, -1.4875709 , -1.4145783 ],
        [-1.18832602, -0.54955101, -0.71952929]],

       ...,

       [[-1.46447887, -0.49538906, -0.94770372],
        [-0

In [146]:
build_model()

WE MADE IT ON EPISODE 0
WE MADE IT ON EPISODE 1
WE MADE IT ON EPISODE 2
WE MADE IT ON EPISODE 3
WE MADE IT ON EPISODE 4
WE MADE IT ON EPISODE 5
WE MADE IT ON EPISODE 6
WE MADE IT ON EPISODE 7
WE MADE IT ON EPISODE 8
WE MADE IT ON EPISODE 9
WE MADE IT ON EPISODE 10
WE MADE IT ON EPISODE 11
WE MADE IT ON EPISODE 12
WE MADE IT ON EPISODE 13
WE MADE IT ON EPISODE 14
WE MADE IT ON EPISODE 15
WE MADE IT ON EPISODE 16
WE MADE IT ON EPISODE 17
WE MADE IT ON EPISODE 18
WE MADE IT ON EPISODE 19
WE MADE IT ON EPISODE 20
WE MADE IT ON EPISODE 21
WE MADE IT ON EPISODE 22
WE MADE IT ON EPISODE 23
WE MADE IT ON EPISODE 24
WE MADE IT ON EPISODE 25
WE MADE IT ON EPISODE 26
WE MADE IT ON EPISODE 27
WE MADE IT ON EPISODE 28
WE MADE IT ON EPISODE 29
WE MADE IT ON EPISODE 30
WE MADE IT ON EPISODE 31
WE MADE IT ON EPISODE 32
WE MADE IT ON EPISODE 33
WE MADE IT ON EPISODE 34
WE MADE IT ON EPISODE 35
WE MADE IT ON EPISODE 36
WE MADE IT ON EPISODE 37
WE MADE IT ON EPISODE 38
WE MADE IT ON EPISODE 39
WE MADE IT

KeyboardInterrupt: 

# Saving The Model

In [147]:
q_table

array([[[ -0.07756931,  -0.32752699,  -0.49295921],
        [ -1.58777135,  -2.40419663,  -2.67250019],
        [-18.03408755, -18.03908231, -17.8301033 ],
        ...,
        [ -0.79812365,  -1.89165595,  -1.21599493],
        [ -0.29315099,  -0.66938371,  -0.13350849],
        [ -1.35507029,  -0.26198008,  -1.60767721]],

       [[ -0.08960482,  -0.55963549,  -0.75136971],
        [-18.01236638, -18.0168762 , -18.02259933],
        [-18.04633231, -18.17706743, -18.17472302],
        ...,
        [ -1.89208149,  -1.57326174,  -0.68347977],
        [ -1.12416492,  -0.53180565,  -0.1720236 ],
        [ -0.37930416,  -0.9518947 ,  -1.26524483]],

       [[ -1.01032751,  -0.4374398 ,  -0.27307617],
        [-18.20749816, -18.25263334, -18.24849359],
        [-18.4244171 , -18.42664098, -18.37383919],
        ...,
        [ -0.24279219,  -0.57675247,  -1.59525209],
        [ -1.65089115,  -1.4875709 ,  -1.4145783 ],
        [ -1.18832602,  -0.54955101,  -0.71952929]],

       ...,

      

In [148]:
ACTIONS

{0: [2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  2,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  1,
  1,
  1],
 1: [2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0

In [149]:
# reshaping the array from 3D
# matrice to 2D matrice.
arr_reshaped = q_table.reshape(q_table.shape[0], -1)
  
# saving reshaped array to file.
np.savetxt("Agent03.txt", arr_reshaped)
  

In [150]:
# retrieving data from file.
loaded_arr = np.loadtxt("Agent03.txt")
  
# This loadedArr is a 2D array, therefore
# we need to convert it to the original
# array shape.reshaping to get original
# matrice with original shape.
load_original_arr = loaded_arr.reshape(20, 20, 3)

load_original_arr

array([[[ -0.07756931,  -0.32752699,  -0.49295921],
        [ -1.58777135,  -2.40419663,  -2.67250019],
        [-18.03408755, -18.03908231, -17.8301033 ],
        ...,
        [ -0.79812365,  -1.89165595,  -1.21599493],
        [ -0.29315099,  -0.66938371,  -0.13350849],
        [ -1.35507029,  -0.26198008,  -1.60767721]],

       [[ -0.08960482,  -0.55963549,  -0.75136971],
        [-18.01236638, -18.0168762 , -18.02259933],
        [-18.04633231, -18.17706743, -18.17472302],
        ...,
        [ -1.89208149,  -1.57326174,  -0.68347977],
        [ -1.12416492,  -0.53180565,  -0.1720236 ],
        [ -0.37930416,  -0.9518947 ,  -1.26524483]],

       [[ -1.01032751,  -0.4374398 ,  -0.27307617],
        [-18.20749816, -18.25263334, -18.24849359],
        [-18.4244171 , -18.42664098, -18.37383919],
        ...,
        [ -0.24279219,  -0.57675247,  -1.59525209],
        [ -1.65089115,  -1.4875709 ,  -1.4145783 ],
        [ -1.18832602,  -0.54955101,  -0.71952929]],

       ...,

      

In [155]:
episodes = 10

for episode in range(1, episodes + 1):
    state = env.reset()
    
    done = False
    score = 0
    while not done:
        env.render()
        discrete_state = get_discrete_state(state)
        action = np.argmax(load_original_arr[discrete_state]) 
        state, reward, done, _ = env.step(action)
        score += reward
    print('Episode: {} Scoure: {}'.format(episode, score))
env.close()

Episode: 1 Scoure: -133.0
Episode: 2 Scoure: -142.0
Episode: 3 Scoure: -134.0
Episode: 4 Scoure: -136.0
Episode: 5 Scoure: -143.0
Episode: 6 Scoure: -142.0
Episode: 7 Scoure: -131.0
Episode: 8 Scoure: -134.0
Episode: 9 Scoure: -113.0
Episode: 10 Scoure: -113.0


# The End

![<caption>](img/end.jpg)